---
- name: This is second playbook
  hosts: all
  tasks:
    - name: Creating a directory
      win_file:
        path: c:\custom_share
        state: directory
    - name: Enabling the sharing
      win_share:
        name: window_share
        description: this is a custom share 
        path: c:\custom_share
        full: administrator
        state: present
    - name: copying some custom content
      win_copy:
        content: "This is a shared content"
        dest: c:\\custom_share\\shared.txt